### ISSUE TITLE
Node server: crash bug

### ISSUE THREAD

**Issue by dwarren4096** [sleepdeprivation/serverside#26]
server.js has a bug related to losing connection to the MySQL database. Attempts at reproduction have been unreliable. Test cases:
**Case 1: MySQL server stopped with `service mysql stop`.** Node server "properly" handles `Error: connect ECONNREFUSED`, stays up, but no additional queries are processed.
**Case 2: MySQL server already stopped, node server attempted to bring up via `service hermes start`.** Node server starts up properly, but handles `Error: connect ECONNREFUSED`.
**Case 3: MySQL server restarted with `service mysql restart`.** Node server crashes hard with:
```
Error: Connection lost: The server closed the connection.
    at Protocol.end (/home/hermes/serverside/node_modules/mysql/lib/protocol/Protocol.js:103:13)
    at Socket.<anonymous> (/home/hermes/serverside/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.emit (events.js:117:20)
    at _stream_readable.js:929:16
    at process._tickCallback (node.js:419:13)
```

**Comment by dwarren4096** [comment]
Additional test cases:  
**Case 1: MySQL server stopped with `service mysql stop`.** Node server properly handles `Error: connect ECONNREFUSED`, stays up, but no additional queries are processed.
**Case 2: MySQL server already stopped, node server attempted to bring up via `service hermes start`.** Node server starts up properly, but handles `Error: connect ECONNREFUSED`.
**Case 3: MySQL server restarted with `service mysql restart`.** Node server crashes hard.
```
Error: Connection lost: The server closed the connection.
    at Protocol.end (/home/hermes/serverside/node_modules/mysql/lib/protocol/Protocol.js:103:13)
    at Socket.<anonymous> (/home/hermes/serverside/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.emit (events.js:117:20)
    at _stream_readable.js:929:16
    at process._tickCallback (node.js:419:13)
```
